[package]

name = "fn_box"
description = "Box up your FnOnces"
version = "1.0.2"
authors = ["Nathan Zadoks <nathan@nathan7.eu>"]
license = "CC0-1.0"
repository = "https://github.com/nathan7/fn_box"
readme = "README.md"
